steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-f"
      - "${_DOCKERFILE_PATH}"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:latest"
      - "${_BUILD_CONTEXT}"

  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA"

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud run deploy "${_SERVICE_NAME}" \
          --image "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA" \
          --region "${_REGION}" \
          --platform managed \
          --port=8080 \
          --timeout=3600 \
          --allow-unauthenticated \
          --set-env-vars "SPRING_DATASOURCE_URL=${_SPRING_DATASOURCE_URL},SPRING_DATASOURCE_USERNAME=${_SPRING_DATASOURCE_USERNAME},SPRING_DATASOURCE_PASSWORD=${_SPRING_DATASOURCE_PASSWORD},APP_JWT_SECRET=${_JWT_SECRET}"

images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:$COMMIT_SHA"
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:latest"

substitutions:
  _REGION: "us-central1"
  _REPO_NAME: "learnhub"
  _SERVICE_NAME: "learnhub-backend"
  _DOCKERFILE_PATH: "backend/Dockerfile"
  _BUILD_CONTEXT: "backend"
  _SPRING_DATASOURCE_URL: "jdbc:mysql://136.113.129.78:3306/lms_elearn_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  _SPRING_DATASOURCE_USERNAME: "lms_user"
  _SPRING_DATASOURCE_PASSWORD: "Nadizeya@123"
  _JWT_SECRET: "ZmFrZV9qb3Nlc19zZWNyZXRfMzJieXRlc19iYXNlNjQ="